type AgentCopyLocale = string | null | undefined;

const agentCopy = {
  en: {
    agents: "Agents",
    selectCompany: "Select a company to view agents.",
    all: "All",
    active: "Active",
    paused: "Paused",
    error: "Error",
    filters: "Filters",
    showTerminated: "Show terminated",
    newAgent: "New Agent",
    createFirstAgent: "Create your first agent to get started.",
    noAgentsMatch: "No agents match the selected filter.",
    noOrgHierarchy: "No organizational hierarchy defined.",
    agent: "Agent",
    runs: "Runs",
    instructions: "Instructions",
    configuration: "Configuration",
    budget: "Budget",
    dashboard: "Dashboard",
    skills: "Skills",
    assignTask: "Assign Task",
    runHeartbeat: "Run Heartbeat",
    live: "Live",
    copyAgentId: "Copy Agent ID",
    resetSessions: "Reset Sessions",
    terminate: "Terminate",
    pendingApproval: "This agent is pending board approval and cannot be invoked yet.",
    cancel: "Cancel",
    save: "Save",
    saving: "Saving…",
    liveRun: "Live Run",
    latestRun: "Latest Run",
    viewDetails: "View details →",
    recentIssues: "Recent Issues",
    seeAll: "See All →",
    noRecentIssues: "No recent issues.",
    costs: "Costs",
    inputTokens: "Input tokens",
    outputTokens: "Output tokens",
    cachedTokens: "Cached tokens",
    totalCost: "Total cost",
    date: "Date",
    run: "Run",
    input: "Input",
    output: "Output",
    cost: "Cost",
    apiKeys: "API Keys",
    configurationRevisions: "Configuration Revisions",
    noConfigurationRevisions: "No configuration revisions yet.",
    restore: "Restore",
    changed: "Changed: ",
    noTrackedChanges: "no tracked changes",
    noRunsYet: "No runs yet.",
    backToRuns: "Back to runs",
    unsavedChanges: "Unsaved changes",
    identity: "Identity",
    name: "Name",
    agentName: "Agent name",
    title: "Title",
    exampleTitle: "e.g. VP of Engineering",
    reportsTo: "Reports to",
    chooseManager: "Choose manager…",
    capabilities: "Capabilities",
    capabilitiesPlaceholder: "Describe what this agent can do...",
    promptTemplate: "Prompt Template",
    promptTemplatePlaceholder: "You are agent {{ agent.name }}. Your role is {{ agent.role }}...",
    promptTemplateHint:
      "Prompt template is replayed on every heartbeat. Keep it compact and dynamic to avoid recurring token cost and cache churn.",
    promptTemplateHintCreate:
      "Prompt template is replayed on every heartbeat. Prefer small task framing and variables like {{ context.* }} or {{ run.* }}; avoid repeating stable instructions here.",
    adapter: "Adapter",
    testing: "Testing...",
    testEnvironment: "Test environment",
    adapterType: "Adapter type",
    environmentTestFailed: "Environment test failed",
    workingDirectoryDeprecated: "Working directory (deprecated)",
    projectPath: "/path/to/project",
    permissionsAndConfiguration: "Permissions & Configuration",
    command: "Command",
    detectModel: "Detect model",
    noModelDetectedSelect: "No model detected. Select or enter one manually.",
    failedLoadAdapterModels: "Failed to load adapter models.",
    bootstrapPromptLegacy: "Bootstrap prompt (legacy)",
    bootstrapPromptPlaceholder: "Optional initial setup prompt for the first run",
    bootstrapPromptHint:
      "Bootstrap prompt is legacy and will be removed in a future release. Consider moving this content into the agent&apos;s prompt template or instructions file instead.",
    extraArgs: "Extra args (comma-separated)",
    extraArgsPlaceholder: "e.g. --verbose, --foo=bar",
    envVars: "Environment variables",
    model: "Model",
    default: "Default",
    selectModelRequired: "Select model (required)",
    selectModel: "Select model",
    searchModelsCreate: "Search models... (type to create)",
    searchModels: "Search models...",
    detecting: "Detecting...",
    redetectFromConfig: "Re-detect from config",
    detectFromConfig: "Detect from config",
    current: "current",
    detected: "detected",
    config: "config",
    useManualModel: "Use manual model",
    noModelDetectedYet: "No model detected yet. Enter a provider/model manually.",
    noModelsFound: "No models found.",
    thinkingEffort: "Thinking effort",
    auto: "Auto",
    addNewAgent: "Add a new agent",
    ceoSetupRecommendation:
      "We recommend letting your CEO handle agent setup — they know the org structure and can configure reporting, permissions, and adapters.",
    askCeoToCreateAgent: "Ask the CEO to create a new agent",
    advancedConfigurationMyself: "I want advanced configuration myself",
    back: "Back",
    advancedAdapterSetup: "Choose your adapter type for advanced setup.",
    recommended: "Recommended",
    createNewAgentIssueTitle: "Create a new agent",
    createNewAgentIssueDescription: "(type in what kind of agent you want here)",
  },
  "zh-CN": {
    agents: "智能体",
    selectCompany: "请选择一个公司以查看智能体。",
    all: "全部",
    active: "运行中",
    paused: "已暂停",
    error: "异常",
    filters: "筛选",
    showTerminated: "显示已终止",
    newAgent: "新建智能体",
    createFirstAgent: "创建你的第一个智能体。",
    noAgentsMatch: "没有符合当前筛选条件的智能体。",
    noOrgHierarchy: "尚未定义组织层级。",
    agent: "智能体",
    runs: "运行",
    instructions: "指令",
    configuration: "配置",
    budget: "预算",
    dashboard: "概览",
    skills: "技能",
    assignTask: "分配任务",
    runHeartbeat: "运行心跳",
    live: "运行中",
    copyAgentId: "复制 Agent ID",
    resetSessions: "重置会话",
    terminate: "终止",
    pendingApproval: "该 Agent 仍在等待看板审批，暂时还不能运行。",
    cancel: "取消",
    save: "保存",
    saving: "保存中…",
    liveRun: "实时运行",
    latestRun: "最近运行",
    viewDetails: "查看详情 →",
    recentIssues: "最近任务",
    seeAll: "查看全部 →",
    noRecentIssues: "最近没有任务。",
    costs: "成本",
    inputTokens: "输入 Tokens",
    outputTokens: "输出 Tokens",
    cachedTokens: "缓存 Tokens",
    totalCost: "总成本",
    date: "日期",
    run: "运行",
    input: "输入",
    output: "输出",
    cost: "成本",
    apiKeys: "API 密钥",
    configurationRevisions: "配置修订记录",
    noConfigurationRevisions: "暂时还没有配置修订记录。",
    restore: "恢复",
    changed: "变更项：",
    noTrackedChanges: "没有记录到字段变化",
    noRunsYet: "暂时还没有运行记录。",
    backToRuns: "返回运行列表",
    unsavedChanges: "有未保存的更改",
    identity: "身份信息",
    name: "名称",
    agentName: "Agent 名称",
    title: "职位",
    exampleTitle: "例如：工程副总裁",
    reportsTo: "汇报对象",
    chooseManager: "选择上级…",
    capabilities: "能力说明",
    capabilitiesPlaceholder: "描述这个 Agent 能做什么…",
    promptTemplate: "Prompt 模板",
    promptTemplatePlaceholder: "你是 Agent {{ agent.name }}，你的角色是 {{ agent.role }}…",
    promptTemplateHint:
      "Prompt 模板会在每次心跳时重新注入。请尽量保持简短、动态，避免反复消耗 token 和破坏缓存。",
    promptTemplateHintCreate:
      "Prompt 模板会在每次心跳时重新注入。这里更适合放简短任务框架，以及 {{ context.* }}、{{ run.* }} 这类变量；不要重复写稳定不变的长说明。",
    adapter: "适配器",
    testing: "测试中…",
    testEnvironment: "测试环境",
    adapterType: "适配器类型",
    environmentTestFailed: "环境测试失败",
    workingDirectoryDeprecated: "工作目录（已废弃）",
    projectPath: "/项目/路径",
    permissionsAndConfiguration: "权限与配置",
    command: "命令",
    detectModel: "检测模型",
    noModelDetectedSelect: "还没有检测到模型，请手动选择或输入。",
    failedLoadAdapterModels: "加载适配器模型失败。",
    bootstrapPromptLegacy: "Bootstrap Prompt（旧版）",
    bootstrapPromptPlaceholder: "首次运行时可选的初始化提示词",
    bootstrapPromptHint:
      "Bootstrap Prompt 属于旧能力，后续版本会移除。建议把这部分内容迁移到 Agent 的 Prompt 模板或指令文件中。",
    extraArgs: "额外参数（逗号分隔）",
    extraArgsPlaceholder: "例如：--verbose, --foo=bar",
    envVars: "环境变量",
    model: "模型",
    default: "默认",
    selectModelRequired: "选择模型（必填）",
    selectModel: "选择模型",
    searchModelsCreate: "搜索模型…（输入后可创建）",
    searchModels: "搜索模型…",
    detecting: "检测中…",
    redetectFromConfig: "重新检测配置",
    detectFromConfig: "从配置检测",
    current: "当前",
    detected: "已检测",
    config: "配置",
    useManualModel: "使用手动输入的模型",
    noModelDetectedYet: "还没有检测到模型，请手动输入 provider/model。",
    noModelsFound: "没有找到模型。",
    thinkingEffort: "思考强度",
    auto: "自动",
    addNewAgent: "添加新智能体",
    ceoSetupRecommendation:
      "建议由 CEO 来完成智能体初始配置——他们更了解组织结构，也能统一设置汇报关系、权限和适配器。",
    askCeoToCreateAgent: "让 CEO 创建新智能体",
    advancedConfigurationMyself: "我想自己做高级配置",
    back: "返回",
    advancedAdapterSetup: "选择用于高级创建流程的适配器类型。",
    recommended: "推荐",
    createNewAgentIssueTitle: "创建一个新的智能体",
    createNewAgentIssueDescription: "请在这里说明你想创建什么样的智能体",
  },
} as const;

function resolveLocale(locale: AgentCopyLocale) {
  return locale === "zh-CN" ? "zh-CN" : "en";
}

export function getAgentCopy(locale: AgentCopyLocale) {
  return agentCopy[resolveLocale(locale)];
}

export function formatAgentCount(count: number, locale: AgentCopyLocale) {
  return locale === "zh-CN" ? `${count} 个智能体` : `${count} agent${count === 1 ? "" : "s"}`;
}

export function formatAgentMoreIssues(count: number, locale: AgentCopyLocale): string {
  if (locale === "zh-CN") {
    return `还有 ${count} 个任务`;
  }
  return `+${count} more issues`;
}

export function agentInvocationSourceLabels(locale: AgentCopyLocale) {
  if (locale === "zh-CN") {
    return {
      timer: "定时",
      assignment: "分配",
      on_demand: "按需",
      automation: "自动化",
    };
  }

  return {
    timer: "Timer",
    assignment: "Assignment",
    on_demand: "On demand",
    automation: "Automation",
  };
}

export function thinkingEffortLabel(
  value: "auto" | "minimal" | "low" | "medium" | "high" | "xhigh" | "max" | "plan" | "ask",
  locale: AgentCopyLocale,
) {
  if (locale !== "zh-CN") {
    return {
      auto: "Auto",
      minimal: "Minimal",
      low: "Low",
      medium: "Medium",
      high: "High",
      xhigh: "X-High",
      max: "Max",
      plan: "Plan",
      ask: "Ask",
    }[value];
  }

  return {
    auto: "自动",
    minimal: "最少",
    low: "低",
    medium: "中",
    high: "高",
    xhigh: "超高",
    max: "最高",
    plan: "规划",
    ask: "问答",
  }[value];
}
