type ProjectCopyLocale = string | null | undefined;

const projectCopy = {
  en: {
    fallbackName: "Project",
    noCompanySelected: "No company selected",
    breadcrumbProjects: "Projects",
    tabs: {
      issues: "Issues",
      overview: "Overview",
      workspaces: "Workspaces",
      configuration: "Configuration",
      budget: "Budget",
    },
    overview: {
      addDescriptionPlaceholder: "Add a description...",
      status: "Status",
      targetDate: "Target Date",
      pausedByBudgetHardStop: "Paused by budget hard stop",
    },
    color: {
      changeProjectColor: "Change project color",
      selectColor: (color: string) => `Select color ${color}`,
    },
    workspaces: {
      emptyState: "No non-default workspace activity yet.",
      start: "Start",
      stop: "Stop",
      close: "Close",
      retryClose: "Retry close",
      pathCopied: "Path copied",
      issues: "Issues",
      moreIssues: (count: number) => `+${count} more`,
      cleanupAttentionNeeded: "Cleanup attention needed",
      loading: "Loading workspaces...",
    },
    archiveToast: {
      archived: (name: string) => `"${name}" has been archived`,
      unarchived: (name: string) => `"${name}" has been unarchived`,
      archiveFailed: "Failed to archive project",
      unarchiveFailed: "Failed to unarchive project",
    },
    saveState: {
      saving: "Saving",
      saved: "Saved",
      failed: "Failed",
    },
    fields: {
      name: "Name",
      description: "Description",
      status: "Status",
      lead: "Lead",
      goals: "Goals",
      env: "Env",
      created: "Created",
      updated: "Updated",
      targetDate: "Target Date",
    },
    statusOptions: {
      backlog: "Backlog",
      planned: "Planned",
      in_progress: "In Progress",
      completed: "Completed",
      cancelled: "Cancelled",
    },
    form: {
      projectNamePlaceholder: "Project name",
      descriptionPlaceholder: "Add a description...",
      noDescription: "No description",
      goal: "Goal",
      allGoalsLinked: "All goals linked.",
      removeGoal: (goalTitle: string) => `Remove goal ${goalTitle}`,
      envDescription: "Applied to all runs for issues in this project. Project values override agent env on key conflicts.",
    },
    codebase: {
      title: "Codebase",
      helpAria: "Codebase help",
      helpTooltip: "Repo identifies the source of truth. Local folder is the default place agents write code.",
      repo: "Repo",
      localFolder: "Local folder",
      notSet: "Not set.",
      setRepo: "Set repo",
      changeRepo: "Change repo",
      clearRepo: "Clear repo",
      setLocalFolder: "Set local folder",
      changeLocalFolder: "Change local folder",
      clearLocalFolder: "Clear local folder",
      paperclipManagedFolder: "Paperclip-managed folder.",
      additionalLegacyWorkspaces:
        "Additional legacy workspace records exist on this project. Paperclip is using the primary workspace as the codebase view.",
      noUrl: "No URL",
      localFolderPlaceholder: "/absolute/path/to/workspace",
      repoUrlPlaceholder: "https://github.com/org/repo",
      save: "Save",
      cancel: "Cancel",
      failedToSaveWorkspace: "Failed to save workspace.",
      failedToDeleteWorkspace: "Failed to delete workspace.",
      failedToUpdateWorkspace: "Failed to update workspace.",
      invalidLocalFolder: "Local folder must be a full absolute path.",
      invalidRepoUrl: "Repo must use a valid GitHub or GitHub Enterprise repo URL.",
      clearLocalFolderConfirm: (hasRepo: boolean) =>
        hasRepo ? "Clear local folder from this workspace?" : "Delete this workspace local folder?",
      clearRepoConfirm: (hasLocalFolder: boolean) =>
        hasLocalFolder ? "Clear repo from this workspace?" : "Delete this workspace repo?",
    },
    executionWorkspaces: {
      title: "Execution Workspaces",
      helpAria: "Execution workspaces help",
      helpTooltip: "Project-owned defaults for isolated issue checkouts and execution workspace behavior.",
      enableIsolatedIssueCheckouts: "Enable isolated issue checkouts",
      enableIsolatedIssueCheckoutsDescription:
        "Let issues choose between the project's primary checkout and an isolated execution workspace.",
      enabled: "Enabled",
      disabled: "Disabled",
      defaultToIsolatedCheckout: "New issues default to isolated checkout",
      defaultToIsolatedCheckoutDescription:
        "If disabled, new issues stay on the project's primary checkout unless someone opts in.",
      showAdvancedCheckoutSettings: "Show advanced checkout settings",
      hideAdvancedCheckoutSettings: "Hide advanced checkout settings",
      hostManagedImplementation: "Host-managed implementation",
      gitWorktree: "Git worktree",
      baseRef: "Base ref",
      branchTemplate: "Branch template",
      worktreeParentDir: "Worktree parent dir",
      provisionCommand: "Provision command",
      teardownCommand: "Teardown command",
      advancedHelp:
        "Provision runs inside the derived worktree before agent execution. Teardown is stored here for future cleanup flows.",
    },
    archive: {
      dangerZone: "Danger Zone",
      archive: "Archive",
      unarchive: "Unarchive",
      archiveDescription: "Archive this project to hide it from the sidebar and project selectors.",
      unarchiveDescription: "Unarchive this project to restore it in the sidebar and project selectors.",
      archiving: "Archiving...",
      unarchiving: "Unarchiving...",
      confirm: "Confirm",
      cancel: "Cancel",
      actionQuestion: (action: string, projectName: string) => `${action} “${projectName}”?`,
      actionButton: (action: string) => `${action} project`,
    },
  },
  "zh-CN": {
    fallbackName: "项目",
    noCompanySelected: "尚未选择公司",
    breadcrumbProjects: "项目",
    tabs: {
      issues: "任务",
      overview: "概览",
      workspaces: "工作区",
      configuration: "配置",
      budget: "预算",
    },
    overview: {
      addDescriptionPlaceholder: "添加描述…",
      status: "状态",
      targetDate: "目标日期",
      pausedByBudgetHardStop: "因预算硬性停机而暂停",
    },
    color: {
      changeProjectColor: "更改项目颜色",
      selectColor: (color: string) => `选择颜色 ${color}`,
    },
    workspaces: {
      emptyState: "还没有非默认工作区活动。",
      start: "启动",
      stop: "停止",
      close: "关闭",
      retryClose: "重试关闭",
      pathCopied: "路径已复制",
      issues: "任务",
      moreIssues: (count: number) => `另有 ${count} 个`,
      cleanupAttentionNeeded: "需要关注清理结果",
      loading: "正在加载工作区…",
    },
    archiveToast: {
      archived: (name: string) => `已归档“${name}”`,
      unarchived: (name: string) => `已恢复“${name}”`,
      archiveFailed: "归档项目失败",
      unarchiveFailed: "恢复项目失败",
    },
    saveState: {
      saving: "保存中",
      saved: "已保存",
      failed: "失败",
    },
    fields: {
      name: "名称",
      description: "描述",
      status: "状态",
      lead: "负责人",
      goals: "目标",
      env: "环境变量",
      created: "创建时间",
      updated: "更新时间",
      targetDate: "目标日期",
    },
    statusOptions: {
      backlog: "待规划",
      planned: "已规划",
      in_progress: "进行中",
      completed: "已完成",
      cancelled: "已取消",
    },
    form: {
      projectNamePlaceholder: "项目名称",
      descriptionPlaceholder: "添加描述…",
      noDescription: "暂无描述",
      goal: "关联目标",
      allGoalsLinked: "所有目标都已关联。",
      removeGoal: (goalTitle: string) => `移除目标 ${goalTitle}`,
      envDescription: "会应用到该项目下所有任务的运行过程。若与 Agent 环境变量同名，项目级配置会覆盖 Agent 配置。",
    },
    codebase: {
      title: "代码库",
      helpAria: "代码库说明",
      helpTooltip: "仓库 URL 用来标记代码真源；本地文件夹是 Agent 默认写入代码的位置。",
      repo: "仓库",
      localFolder: "本地目录",
      notSet: "未设置。",
      setRepo: "设置仓库",
      changeRepo: "更换仓库",
      clearRepo: "清空仓库",
      setLocalFolder: "设置本地目录",
      changeLocalFolder: "更换本地目录",
      clearLocalFolder: "清空本地目录",
      paperclipManagedFolder: "由 Paperclip 管理的目录。",
      additionalLegacyWorkspaces: "该项目还存在其他历史工作区记录。当前代码库视图使用的是主工作区。",
      noUrl: "无 URL",
      localFolderPlaceholder: "/absolute/path/to/workspace",
      repoUrlPlaceholder: "https://github.com/org/repo",
      save: "保存",
      cancel: "取消",
      failedToSaveWorkspace: "保存工作区失败。",
      failedToDeleteWorkspace: "删除工作区失败。",
      failedToUpdateWorkspace: "更新工作区失败。",
      invalidLocalFolder: "本地目录必须是完整的绝对路径。",
      invalidRepoUrl: "仓库 URL 必须是有效的 GitHub 或 GitHub Enterprise 仓库地址。",
      clearLocalFolderConfirm: (hasRepo: boolean) =>
        hasRepo ? "要从当前工作区清空本地目录吗？" : "要删除该工作区的本地目录吗？",
      clearRepoConfirm: (hasLocalFolder: boolean) =>
        hasLocalFolder ? "要从当前工作区清空仓库配置吗？" : "要删除该工作区的仓库配置吗？",
    },
    executionWorkspaces: {
      title: "执行工作区",
      helpAria: "执行工作区说明",
      helpTooltip: "配置项目级默认值，用于控制独立 issue checkout 和执行工作区行为。",
      enableIsolatedIssueCheckouts: "启用独立任务 checkout",
      enableIsolatedIssueCheckoutsDescription: "允许任务在项目主 checkout 与独立执行工作区之间选择。",
      enabled: "已启用",
      disabled: "已停用",
      defaultToIsolatedCheckout: "新任务默认使用独立 checkout",
      defaultToIsolatedCheckoutDescription: "关闭后，新任务默认留在项目主 checkout，除非有人手动启用独立工作区。",
      showAdvancedCheckoutSettings: "显示高级 checkout 设置",
      hideAdvancedCheckoutSettings: "隐藏高级 checkout 设置",
      hostManagedImplementation: "宿主管理实现",
      gitWorktree: "Git worktree",
      baseRef: "基础分支",
      branchTemplate: "分支模板",
      worktreeParentDir: "Worktree 父目录",
      provisionCommand: "初始化命令",
      teardownCommand: "回收命令",
      advancedHelp: "初始化命令会在派生 worktree 内、Agent 执行前运行。回收命令会保存在这里，供后续清理流程使用。",
    },
    archive: {
      dangerZone: "危险操作区",
      archive: "归档",
      unarchive: "恢复",
      archiveDescription: "归档后，项目会从侧边栏和项目选择器中隐藏。",
      unarchiveDescription: "恢复后，项目会重新出现在侧边栏和项目选择器中。",
      archiving: "归档中...",
      unarchiving: "恢复中...",
      confirm: "确认",
      cancel: "取消",
      actionQuestion: (action: string, projectName: string) => `${action}“${projectName}”？`,
      actionButton: (action: string) => `${action}项目`,
    },
  },
} as const;

function resolveLocale(locale: ProjectCopyLocale) {
  return locale === "zh-CN" ? "zh-CN" : "en";
}

export function getProjectCopy(locale: ProjectCopyLocale) {
  return projectCopy[resolveLocale(locale)];
}

export function projectStatusOptions(locale: ProjectCopyLocale) {
  const copy = getProjectCopy(locale);
  return [
    { value: "backlog", label: copy.statusOptions.backlog },
    { value: "planned", label: copy.statusOptions.planned },
    { value: "in_progress", label: copy.statusOptions.in_progress },
    { value: "completed", label: copy.statusOptions.completed },
    { value: "cancelled", label: copy.statusOptions.cancelled },
  ] as const;
}
