// Row shapes handed to the batched company-import writers.
//
// Company import resolves every entity up front (slugs → ids, label remaps,
// status downgrades, blob verification, embedded-asset rewrites) and then hands
// fully-resolved rows to these writers, which insert them in chunked multi-row
// statements. Ids are pre-generated by the caller so children can reference
// their parents without a per-row `.returning()` round-trip.

import type {
  IssueCommentAuthorType,
  IssueCommentMetadata,
  IssueCommentPresentation,
  IssuePriority,
  IssueStatus,
  SourceTrustMetadata,
} from "@paperclipai/shared";

/** A resolved issue row with a pre-generated id, ready for batch insert. */
export interface ImportIssueRow {
  /** Pre-generated issue id (app-supplied uuid). */
  id: string;
  /** Source slug, so the caller can correlate the row after the batch. */
  ref: string;
  projectId: string | null;
  projectWorkspaceId: string | null;
  title: string;
  description: string | null;
  assigneeAgentId: string | null;
  status: IssueStatus;
  priority: IssuePriority;
  billingCode: string | null;
  assigneeAdapterOverrides: Record<string, unknown> | null;
  executionWorkspaceSettings: Record<string, unknown> | null;
  labelIds: string[];
  /** Imported monitors land un-armed; only notes/provenance are restored. */
  monitorNotes: string | null;
  monitorScheduledBy: string | null;
}

/** A resolved comment row with a pre-generated id, ready for batch insert. */
export interface ImportIssueCommentRow {
  id: string;
  companyId: string;
  issueId: string;
  body: string;
  authorType: IssueCommentAuthorType;
  authorAgentId: string | null;
  authorUserId: string | null;
  presentation: IssueCommentPresentation | null;
  metadata: IssueCommentMetadata | null;
  createdAt: Date | string | null;
}

/** A resolved attachment (asset + link) row, ready for batch insert. */
export interface ImportIssueAttachmentRow {
  companyId: string;
  issueId: string;
  issueCommentId: string | null;
  provider: string;
  objectKey: string;
  contentType: string;
  byteSize: number;
  sha256: string;
  originalFilename: string | null;
  createdByAgentId: string | null;
  createdByUserId: string | null;
}

/** A resolved issue-document row, ready for batch insert. */
export interface ImportIssueDocumentRow {
  companyId: string;
  issueId: string;
  key: string;
  title: string | null;
  format: string;
  body: string;
  createdByAgentId: string | null;
  createdByUserId: string | null;
  createdByRunId: string | null;
  sourceTrust: SourceTrustMetadata | null;
}

/** A resolved work-product row, ready for batch insert. */
export interface ImportIssueWorkProductRow {
  companyId: string;
  issueId: string;
  projectId: string | null;
  type: string;
  provider: string;
  externalId: string | null;
  title: string;
  url: string | null;
  status: string;
  reviewState: string;
  isPrimary: boolean;
  healthStatus: string;
  summary: string | null;
  metadata: Record<string, unknown> | null;
  executionWorkspaceId: string | null;
  runtimeServiceId: string | null;
  createdByRunId: string | null;
  sourceTrust: SourceTrustMetadata | null;
}
